// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHgok_70-PrF4fzKyoAMleFd5tpoiwH-Y',
    appId: '1:51563568011:web:135c5a4ad14ca6569e6d8e',
    messagingSenderId: '51563568011',
    projectId: 'todo-tiles',
    authDomain: 'todo-tiles.firebaseapp.com',
    storageBucket: 'todo-tiles.appspot.com',
    measurementId: 'G-KYBW3REQXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_CXpvIai5AhYWEfMOQZ7mRSa0wG2Guc',
    appId: '1:51563568011:android:cb7ff06cabe054729e6d8e',
    messagingSenderId: '51563568011',
    projectId: 'todo-tiles',
    storageBucket: 'todo-tiles.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLI8ZcD97BbZCSuXSRAN6mQteHJINNTbk',
    appId: '1:51563568011:ios:f4cc5ead8444317c9e6d8e',
    messagingSenderId: '51563568011',
    projectId: 'todo-tiles',
    storageBucket: 'todo-tiles.appspot.com',
    iosClientId: '51563568011-lmi3o5e1s7p9agtmeq8qg46u80lrecli.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoTiles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLI8ZcD97BbZCSuXSRAN6mQteHJINNTbk',
    appId: '1:51563568011:ios:16973a3ecd91c42b9e6d8e',
    messagingSenderId: '51563568011',
    projectId: 'todo-tiles',
    storageBucket: 'todo-tiles.appspot.com',
    iosClientId: '51563568011-f84ke5b252sagrs8onpgr807toguoghi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoTiles.RunnerTests',
  );
}
